MVCHomeWord/MoneyMVC/Models/ViewModels/MoneyViewModel.cs
using MoneyMVC.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace MoneyMVC.Models.ViewModels
{
    public class MoneyViewModel
    {
        [Required(ErrorMessage = "請選擇類別")]
        public CategoryType Type { get; set; }

        [Required(ErrorMessage = "請輸入日期")]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "請填入金額")]
        [DisplayFormat(DataFormatString = "{0:n0}")]
        public int Price { get; set; }

        [Required(ErrorMessage = "請輸入備註")]
        public string Description { get; set; }
    }
}

MVCHomeWord/MoneyMVC/Controllers/MoneyController.cs
using MoneyMVC.Enums;
using MoneyMVC.Extensions;
using MoneyMVC.Models.ViewModels;
using MoneyMVC.Repository;
using MoneyMVC.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace MoneyMVC.Controllers
{
    public class MoneyController : Controller
    {
        private readonly MoneyService _imoneyService;
        private readonly UnitOfWork _unitOfWork;

        public MoneyController()
        {
            _unitOfWork = new UnitOfWork();
            _imoneyService = new MoneyService(_unitOfWork);
        }

        // GET: Money
        public ActionResult Index()
        {
            ViewData["CategoryItems"] = GetCategoryList();
            ViewData["PageItems"] = GetPageDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "Type,Date,Price,Description")]
                                   MoneyViewModel model)
        {


            /***不知道為什麼model裡面的Type都是None???***/
            if (ModelState.IsValid)
            {
                _imoneyService.Add(model);
                _unitOfWork.Commit();
                return RedirectToAction("Index");
            }

            return View(model);
        }

       // [ChildActionOnly]
        public ActionResult ListAction(int page)
        {
            int pagesize = 10;
            var result = _imoneyService.LookupByPageList(page, pagesize);

            return View(result);
        }

        private SelectList GetPageDropDownList()
        {
            int pagesize = 10;
            var sources = _imoneyService.LookupAllData();

            var pageResult = sources.Select((item, inx) => new { item, inx })
                                 .GroupBy(x => x.inx / pagesize)
                                 .Select(g => g.Select(s => s.item));

            var _resources = pageResult.Select((p,inx) => new PageDropDownListViewModel
            {
                name = inx + 1,
                value = inx
            });


            return new SelectList(_resources,"value","name",0);


        }

        private IList<SelectListItem> GetCategoryList()
        {
            return EnumHelper.GetSelectList(typeof(CategoryType));
        }

    }
}

MVCHomeWord/MoneyMVC/Views/Money/Index.cshtml
@model MoneyMVC.Models.ViewModels.MoneyViewModel
@{

    ViewBag.Title = "Home Page";
    int pagevalue = 0;
}

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    <div class="well">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => Model.Type, "類別", htmlAttributes: new { @class = "col-md-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownList("Type", (IEnumerable<SelectListItem>)ViewData["CategoryItems"], new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Price, "金額", htmlAttributes: new { @class = "col-md-2 control-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @Value = "", @placeholder = "金額" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, "日期", htmlAttributes: new { @class = " col-md-2 control-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @Value = "", @placeholder = "日期" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, "備註", htmlAttributes: new { @class = " col-md-2 control-label" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(model => model.Description, 0, 0, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-11 col-sm-4">
                    <button onclick="return confirm('是否確定新增');" class="btn btn-default">送出</button>
                </div>
            </div>
        </div>
    </div>
}

@Html.Action("ListAction", "Money", new { page = 100 })

<div class="form-group">
    <label for="pageList" class="col-sm-2 control-label">頁碼</label>
    <div class="col-sm-10">
        @Html.DropDownList("PageList", (IEnumerable<SelectListItem>)ViewData["PageItems"], new { @class = "form-control", @id = "pagelist", @onchange = "pagechange()" })

    </div>
</div>
@*不知道為什麼下拉選單有觸發/Money/ListAction但是卻沒有換頁效果*@

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function pagechange() {
            var x = document.getElementById("pagelist");
            x.value = x.value.toUpperCase();
            $.ajax({
                url: '/Money/ListAction',
                Type: "GET",
                data: { page: x.value },
                contentType: "application/json; charset=utf-8",
                dataType: "HTML",
                success: function (response) {
                    $("#moneylist").html(response);
                }
            });
        }
    </script>
}




MVCHomeWord/MoneyMVC/Views/Money/ListAction.cshtml
@using MoneyMVC.Extensions

@model IEnumerable<MoneyMVC.Models.ViewModels.MoneyViewModel>
@{
    Layout = null;
    var index = 1;
}

    <div class="row" id="moneylist">
        <div class="col-md-12">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>#</th>
                    <th>類別</th>
                    <th>日期</th>
                    <th>金額</th>
                </tr>
                @{
                    foreach (var m in Model)
                    {

                        var color = m.Type == MoneyMVC.Enums.CategoryType.Income ? "blue" : "red";

                        <tr style="color:@color">
                            <td>@index</td>
                            <td>@(m.Type.GetDisplayName())</td>
                            <td>@Html.DisplayFor(modelitem => m.Date)</td>
                            <td>@Html.DisplayFor(modelitem => m.Price)</td>
                        </tr>
                        index++;
                    };
                }

            </table>
        </div>
    </div>



MVCHomeWord/MoneyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("我的記賬本", "Index", "Money", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SkillTree</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>